#!/bin/bash

#Jack-mixer inputs
#----Headset
jack_connect 'jack_mixer:Headset' 'system:capture_1';
#----MAudio - General
jack_connect 'MAudioIn:capture_1' 'jack_mixer:MTrack-G-1';
jack_connect 'MAudioIn:capture_2' 'jack_mixer:MTrack-G-2';
#----MAudio - Playback
jack_connect 'MAudioIn:capture_1' 'jack_mixer:MTrack-P-1 L';
jack_connect 'MAudioIn:capture_1' 'jack_mixer:MTrack-P-1 R';
jack_connect 'MAudioIn:capture_2' 'jack_mixer:MTrack-P-2 L';
jack_connect 'MAudioIn:capture_2' 'jack_mixer:MTrack-P-2 R';

#Jack-mixer outputs
#----Headset
jack_connect 'jack_mixer:Headset Out' 'PulseAudio JACK Source:front-left';
jack_connect 'jack_mixer:Headset Out' 'PulseAudio JACK Source:front-right';
#----MAudio - General
jack_connect 'jack_mixer:MTrack-G-1 Out' 'PulseAudio JACK Source:front-left';
jack_connect 'jack_mixer:MTrack-G-2 Out' 'PulseAudio JACK Source:front-right';
#----MAudio - Playback
jack_connect 'jack_mixer:MTrack-P-1 Out L' 'system:playback_1';
jack_connect 'jack_mixer:MTrack-P-1 Out R' 'system:playback_2';
jack_connect 'jack_mixer:MTrack-P-2 Out L' 'system:playback_1';
jack_connect 'jack_mixer:MTrack-P-2 Out R' 'system:playback_2';
#----PA Sink - System
jack_connect 'PulseAudio JACK Sink:front-left' 'system:playback_1'
jack_connect 'PulseAudio JACK Sink:front-right' 'system:playback_2'
#----PA Sink - Maudio Out
jack_connect 'PulseAudio JACK Sink:front-left' 'MAudioOut:playback_1'
jack_connect 'PulseAudio JACK Sink:front-right' 'MAudioOut:playback_2'
