#!/bin/bash
# workspaces_icons=":::::::"
# workspaces_icons="\u602:::::::"
workspaces_icons="0:1:2:3:4:5:6:7"

function get-group-data(){
	data_name="$2"
	
	case $data_name in
		loaded)
			[ "$(echo "$3" | grep "'focus'" | cut -d ':' -f2 | tr -d ',' | tr -d ' ')" = 'None' ] && echo 'false' || echo 'true'
		;;
		monitor) 
			echo "$3" | grep "'screen'" | cut -d ':' -f2 | tr -d ',' | tr -d ' '
		;;
	 esac
}

count=0;
while read -r icon; do
	#TODO: loaded esta al pedo, hay que contar la cantidad de windows y mandarla
	group_json=$(qtile cmd-obj -o group "$count" -f info);
	monitor=$(get-group-data "$count" monitor "$group_json");
	loaded=$(get-group-data "$count" loaded "$group_json");
	alert='false'
	windows=3
	#TODO: change icons structure to: assets/workspace-icons/<environment>/icon-<0/1>.png
	yuck="$yuck (workspace-item :index '$icon' :monitor '$monitor' :alert $alert :windows $windows :loaded $loaded)"
	count=$((count+1))
done <<<"$(echo $workspaces_icons | tr ':' '\n')"

#Final return 
echo -e "(box :class 'workspace-selector' :vexpand true :orientation 'vertical' $yuck)"

#Listening for changes
if [ -z "$1" ]; then
	 ncat -lnkp 13255 
else
	 echo -e "(box :class 'workspace-selector' :vexpand true :orientation 'vertical' $yuck)" | ncat localhost 13255
fi
