#!/usr/bin/python3
import subprocess
import json
import os

workspaces_count = 7

# Initializing the workspaces (empty)
total_workspaces = [{"id": i, "screenID": -1, "windows": 0,"alert":False} for i in range(0, workspaces_count+1)]

# Getting the real workspaces from hyprctl
command = subprocess.Popen(["hyprctl", "workspaces", "-j"], stdout=subprocess.PIPE)
output = command.communicate()[0]
workspaces = json.loads(output)

# Getting the current workspace from hyprctl
command = subprocess.Popen(["hyprctl", "activeworkspace", "-j"], stdout=subprocess.PIPE)
output = command.communicate()[0]
active_workspace = json.loads(output)

# Setting active workspace (-1 because hyprland does not allow workspace 0)
total_workspaces[active_workspace["id"] - 1]['screenID'] = 0

# Merging the workspaces with the empty workspaces
for workspace in workspaces:
    total_workspaces[workspace["id"] - 1]['windows'] = workspace['windows'] # (-1 because hyprland does not allow workspace 0)
    # total_workspaces[workspace["id"]]['alert'] = workspace['alert']
    
# Creating the yuck variable
yuck="(defvar screen-0 0)\n\n"
for workspace in total_workspaces:
    # Extracting the data from the workspace
    idx = workspace["id"]
    windows = workspace["windows"]
    # alert = workspace["alert"]
    
    # Updating the yuck variable
    yuck += f'(defvar ws-data{idx}-alert false)\n(defvar ws-data{idx}-windows {windows})\n(defvar ws-data{idx}-icon "assets/workspaces/default/workspace{idx}")\n\n'

# Saving yuck variable to variables.yuck file
with open(os.path.dirname(os.path.realpath(__file__)) + "/../yuck/variables.yuck", "w") as f:
    f.write(yuck)
