#!/bin/bash
eww kill;
pkill waybar;
cd /home/js/.config/eww/scripts || exit 1;
# ./listeners stop;
./listeners start;
./create-variables;
./create-workspaces;
# ./set-resolution;
eww daemon;
eww open bar;
eww open env-selector;
waybar -c /home/js/.config/waybar/tray_config -s /home/js/.config/waybar/style.css
