#!/bin/bash
function usage {
       echo "Usage: dfi -s dotfiles_path [-c config_file][-v]
         -s                          path of the dotfiles DIRECTORY.
         -c                          config file (mapping) 
                                     format:
                                          src:destination
                                          src:destination
                                          src:destination
                                          EOF
                                   [default: dotfiles_path/.dfirc]
         -h                          Display this help message.
         -m                          Create missing destination directories.
         -v                          Increase verbosity level

dfi installs all the dotfiles mapped at .dfirc in the source folder"
       exit 0
}

#Getting params
dotfiles_path='/home/js/.config/dotfiles/'; #default value
config_file='';
export _V=0;
export _M=0;

while getopts :s:c:mvh opt; do
    case ${opt} in
      s) dotfiles_path=${OPTARG};;
      c) config_file=${OPTARG};;
      m) _M=1;;
      h) usage ;;
      v) _V=1;;
      *) echo >&2 "[x] Invalid Option";usage;;
     esac
done

#Validating dotfiles path
if [[ -z "$dotfiles_path" ]] || ! [[ -d "$dotfiles_path" ]]; then
	usage;
fi

#Verbosity
function log () {
    if [[ $_V -eq 1 ]]; then
        echo "$@"
    fi
}
export -f log;

function can_write_path() {
       check_path="$1"

       if [[ -z "$check_path" ]]; then
              return 1
       fi

       if [[ -d "$check_path" ]]; then
              [[ -w "$check_path" && -x "$check_path" ]]
              return $?
       fi

       parent="$check_path"
       while [[ ! -e "$parent" && "$parent" != "/" ]]; do
              parent=$(dirname "$parent")
       done

       if [[ -d "$parent" ]]; then
              [[ -w "$parent" && -x "$parent" ]]
              return $?
       fi

       return 1
}
export -f can_write_path;

#Validating config file
if [[ -z $config_file ]]; then
       log "[!] No config file specified, using $dotfiles_path.dfirc..."
       config_file=$dotfiles_path.dfirc
fi
if ! [[ -f $config_file ]]; then >&2 echo "[x] No valid config file found ($config_file), exiting...";exit 1; fi

#link subfile function
function linkfile(){
       if [[ $# -gt 2 ]]; then 
              sourcefile=${1/$3/$2};targetfile=$1;
       else
              sourcefile=$1;targetfile=$2
       fi
       log "[+] Linking File: $sourcefile -> $targetfile";
       source_dir=$(dirname "$sourcefile")

       if [[ ! -d "$source_dir" ]]; then
              if [[ $_M -eq 1 ]]; then
                     mkdir -p "$source_dir"
              else
                     echo "[!] Skipping $sourcefile: destination directory does not exist ($source_dir). Use -m to create it."
                     return 0
              fi
       fi

       [[ -f $sourcefile ]] && rm "$sourcefile";
       ln -sf "$(realpath "$targetfile")" "$sourcefile";
}
export -f linkfile;

list=$(cat $config_file);

#Check if sudo
if [ "$EUID" -eq 0 ]; then
       read -p "[!] Running as sudo, the \$HOME variable will be pointing to /root, do you want to exclude the paths including it? [Y/n]: " -r
       rs=${REPLY:l};
       if [[ $rs =~ ^(yes|y| ) ]] || [[ -z $rs ]]; then list=$(cat $config_file | grep -v "\$HOME"); fi
       echo $list;
fi

echo -e "[!] WARNING! Every file at:";
echo '-------------------';
echo $list | tr ' ' '\n' | awk -F ':' "{print \$1}" | sed 's,$HOME,'"$HOME,";
echo '-------------------';
read -p "will be overwrited with a symlink pointing to the specified dotfiles directory ($dotfiles_path), do you want to continue? [y/N]: " -r
rs=${REPLY:l};
if ! [[ $rs =~ ^(yes|y| ) ]] || [[ -z $rs ]]; then
    exit 0;
fi

#Logic
log "[+] Linking..."
for line in $list;
do
       tmp_source=$(echo "$line" | cut -d ":" -f 1);
       source=${tmp_source/"\$HOME"/$HOME}
       target=$dotfiles_path$(echo $line | cut -d ":" -f 2);
       write_dir=""

       if [[ -d $target ]]; then
              write_dir="$source"
       elif [[ -f $target ]]; then
              write_dir="$(dirname "$source")"
       elif [ -f "$source" ] && [ ! -f "$target" ]; then
              write_dir="$(dirname "$source")"
       fi

       if [[ -n "$write_dir" ]] && ! can_write_path "$write_dir"; then
              echo "[!] Skipping $source: no write permission in $write_dir (run with sudo if needed)."
              continue
       fi

       #If its a directory, links the subfiles
       if [[ -d $target ]]; then
              log "[+] Linking directory: $source -> $target";
              if [[ ! -d "$source" ]]; then
                     if [[ $_M -eq 1 ]]; then
                            mkdir -p "$source";
                     else
                            echo "[!] Skipping $source: destination directory does not exist. Use -m to create it."
                            continue
                     fi
              fi
              find $target -type f -exec bash -c "linkfile \"{}\" $source $target" \;
              #Clears broken symlinks (Symlinks pointing to nonexistent files)
        	  # find -L $source -type l -exec rm {} \;
       #If it is a file, link the file
       elif [[ -f $target ]]; then
          linkfile $source $target;
       #When linking files, copy it if not exists in dotfiles folder 
       #(This allows install the dotfile only by putting it in the .dfirc file)
       elif [ -f $source ] && [ ! -f $target ]; then
       		mkdir -p "$(dirname "$target")";
       		cp $source $target;
       		linkfile $source $target;
       fi
done
