#!/bin/bash
function usage {
       echo "Usage: dfinstall -s dotfiles_path [-c config_file] [-f]
         -s                          path of the dotfiles DIRECTORY.
         -c                          config file (mapping) 
                                     format:
                                          src:destination
                                          src:destination
                                          src:destination
                                          EOF
                                   [default: dotfiles_path/.linkmap]
         -f                          Force creation if file doesn't exists     
         -h                          Display this help message.

dfinstall installs all the dotfiles mapped at .linkmap in the source folder"
       exit 0
}

#Getting params
dotfiles_path='';
config_file='';
force=false;
while getopts :s:c:fh opt; do
    case ${opt} in
      s) dotfiles_path=${OPTARG};;
      c) config_file=${OPTARG};;
      f) force=true;;
      h) usage ;;
      *) echo "Invalid Option";usage;;
     esac
done

#Validating dotfiles path
if [[ -z "$dotfiles_path" ]] || ! [[ -d "$dotfiles_path" ]]; then
	usage;
fi

#Validating config file
if [[ -z $config_file ]]; then
       echo "[+] No config file specified, using $dotfiles_path.linkmap..."
       config_file=$dotfiles_path.linkmap
       if ! [[ -f $config_file ]]; then echo "[!] No valid config file found, exiting...";exit 1; fi
fi

#link subfile function
function linkfile(){
       if [[ $# -gt 2 ]]; then 
              sourcefile=${1/$3/$2};targetfile=$1
       else
              sourcefile=$1;targetfile=$2
       fi
       
       if [[ -f $sourcefile ]] || ! [[ -f $sourcefile ]] && $force; then
              echo "[+] Linking File: $sourcefile -> $targetfile";
              [[ -f $sourcefile ]] && rm "$sourcefile";
              mkdir -p $(realpath $(dirname $sourcefile));
              ln -sf $(realpath $targetfile) "$sourcefile";
       else
              echo "[!] File not found (Use -f to force creation of file): $sourcefile";
       fi
}
export -f linkfile;

#Logic
echo "[+] Linking..."
while read -r line; 
do
       tmp_source=$(echo "$line" | cut -d ":" -f 1);
       source=${tmp_source/"\$HOME"/$HOME}
       target=$dotfiles_path$(echo $line | cut -d ":" -f 2);
       #If its a directory, links the subfiles
       if [[ -d $target ]]; then
              echo "[+] Linking directory: $source -> $target";
              find $target -type f -exec bash -c "linkfile \"{}\" $source $target" \;
       elif [[ -f $target ]]; then
              linkfile $source $target;
       fi
done < $config_file





