#!/bin/bash

echo $1
webhook_url='https://discord.com/api/webhooks/1215721030564184137/jfibQyI18dybvXx_8Q7m_cP_Hfl2LAlFZE6ENPIi8PsqZWCm58JC45i2blVCJ9_z3f5I'

pl="{\"attachments\":[],\"content\":\"$1\",\"embeds\":null}"

curl "$webhook_url" -d $pl -H 'Content-Type: application/json'

