#!/bin/bash

echo $1
webhook_url='https://discord.com/api/webhooks/1331567274712109096/t1pk1c90_ezV30BbY4Xm-DZa_uoGDypP__vSKD3xtPlhvKtC1_ISJssOELUPVZinCcBz'

pl="{\"attachments\":[],\"content\":\"$1\",\"embeds\":null}"

curl "$webhook_url" -d $pl -H 'Content-Type: application/json'

