#!/bin/zsh -i
cmd=$(history | fzf --height ${FZF_TMUX_HEIGHT:-40%} --tac --no-sort | awk '{$1=""; print $0}')
current_cols=$(stty size | awk '{print $2}');
target_cols=65;
step=$(expr $target_cols - $current_cols)
kitty @ resize-window -i "$step"
name="$(cat /dev/urandom | tr -dc '[:alpha:]' | fold -w ${1:-20} | head -n 1).sh"
echo -e "$cmd" > "/tmp/$name"
shfmt --write -ci -bn -fn -ln bash "/tmp/$name"
micro "/tmp/$name" && kitty @ send-text -m recent:1 "$(cat /tmp/$name)"

