#!/bin/bash
# & alacritty-themes $(shuf -n 1 /home/js/.config/alacritty/themes)
xwinwrap -b -fdt -fs -sp -fs -nf -ov -- wal --saturate 0.35 --backend haishoku --iterative -e -q -i /home/js/documents/wallpapers
