#!/bin/bash

function checkIp {
  # Checking that the ip was fetched correctly
  if [ -z "$1" ]; then
    echo '[x] There was an error fetching the ip, exiting...'
    exit 1
  else
    echo "[+] Ok: $1"
  fi
}

echo "[+] Fetching PC's public IP";
pc_pubip=$(ssh -o ConnectTimeout=10 "$vpc" "curl -s ifconfig.me/ip" 2>/dev/null);

# Checking that the ip was fetched correctly
checkIp "$pc_pubip"

echo "[+] Fetching NB's public IP";
nb_pubip=$(curl -ks ifconfig.me/ip);

# Checking that the ip was fetched correctly
checkIp "$nb_pubip"

# Adding the rule to the sever
ssh -o ConnectTimeout=10 "$vpc" "sudo ufw allow from $nb_pubip to any port 22 proto tcp; sudo ufw reload";

# Checking that the rules were updated correctly
if [ $? -ne 0 ]; then
  echo '[x] There was an error updating the ufw rules, exiting...'
  exit 1
fi

# Logging with the public ip
ssh -o ConnectTimeout=10 "$pc_pubip" 2>/dev/null || echo '[x] There was an error logging with the public ip, exiting...'

