#!/bin/bash

# Denying anything by default
sudo ufw default deny incoming;
sudo ufw default allow outgoing;

# Accepting all traffic inside the zero-tier vpn
sudo ufw allow in on ztuku34z3e

# Accepting all traffic inside the htb-vpn
sudo ufw allow in on tun0

# Applying the changes
sudo ufw enable || sudo ufw reload;
