#!/bin/bash

#Checking that everything's okay
{ ! [ -d ~/bridge ] || [ -z "$1" ];} && exit 1

#Checking if argument is valid and setting variables
if [ "$1" -eq 0 ]; then 
	device='pc';
	devicename='Desktop-Pc';
fi

if [ "$1" -eq 1 ]; then
	device='nb';
	devicename='Notebook';
fi

{ [ -z "$device" ] || [ -z "$devicename" ];} && exit 1

#Pulling changes from repo
cd ~/bridge || exit 1;
git pull;

#Updating data locally
cd "/home/js/bridge/data/$device" || exit 1;

dig +short myip.opendns.com @resolver1.opendns.com > public-ip
ip a | grep 192.168 | awk "{print \$2}" > private-ip

#Pushing changes
git add .;
git commit -m "$(date '+%Y-%m-%d %H:%M:%S'): Updated -> $devicename";
git push;
