#!/bin/bash

#Checking that first parameter is a valid path
if [ ! -d "$1" ]; then
    echo "Error: $1 is not a valid path"
    exit 1
fi

root_dir="$1";

# Change directory to root_dir
cd "$root_dir" || exit; 

# Start front end
export NODE_OPTIONS=--openssl-legacy-provider;
npx ng s;
